sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.4"
  - "3.4.2"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash # Failing
  - haxelib run travix js
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
  # - haxelib run travix lua #see https://github.com/back2dos/travix/issues/78

