version: "{build}"

environment:
    global:
         PYTHON_VERSION: "3.x.x"

install:
  - cinst haxe -y
  - cinst curl -y
  - cinst php -y
  - cmd: mklink C:\Python34-x64\python3.exe C:\Python34-x64\python.exe
  - set PATH=%PATH%;C:\Python34-x64
  - RefreshEnv
  - python --version
  - php -version
  - haxelib setup %HOME%/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

test_script:
  - haxe hxml/test-all-win.hxml