version: "{build}"

environment:
    global:
         PYTHON_VERSION: "3.x.x"

install:
  - cinst haxe -y
  - cinst curl -y
  - cinst php -y
  - cmd: mklink C:\Python34-x64\python3.exe C:\Python34-x64\python.exe
  - set PATH=%PATH%;C:\Python34-x64
  - RefreshEnv
  - python --version
  - php -version
  - haxelib setup %HOME%/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

build_script:
  - echo "[Building NEKO]"
  - haxe tests.hxml -neko bin/test.n
  - echo "[Building JAVASCRIPT]"
  - haxe tests.hxml -js bin/test.js
  - echo "[Building PHP]"
  - haxe tests.hxml -php bin/php
  - echo "[Building PHP7]"
  - haxe tests.hxml -D php7 -php bin/php7
  - echo "[Building PYTHON]"
  - haxe tests.hxml -python bin/test.py
  - echo "[Building JAVA]"
  - haxe tests.hxml -java bin/java
  - echo "[Building C#]"
  - haxe tests.hxml -cs bin/cs
  - echo "[Building C++]"
  - haxe tests.hxml -cpp bin/cpp

test_script:
  - echo "[Running NEKO]"
  - neko bin/test.n
  - echo "[Running JAVASCRIPT]"
  - nodejs bin/test.js
  - echo "[Running PHP]"
  - php bin/php/index.php
  - echo "[Running PHP7]"
  - php bin/php7/index.php
  - echo "[Running PYTHON]"
  - python bin/test.py
  - echo "[Running JAVA]"
  - java -jar bin/java/TestAll.jar
  - echo "[Running C#]"
  - bin/cs/bin/TestAll.exe
  - echo "[Running C++]"
  - bin/cpp/TestAll.exe