version: "{build}"

environment:
    global:
         PYTHON_VERSION: "3.x.x"

install:
  - cinst haxe -y
  - cinst curl -y
  - cinst php -y
  - cmd: mklink C:\Python34-x64\python3.exe C:\Python34-x64\python.exe
  - set PATH=%PATH%;C:\Python34-x64
  - RefreshEnv
  - python --version
  - php -version
  - haxelib setup %HOME%/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

build_script:
  - REM [Building NEKO]
  - haxe tests.hxml -neko bin/test.n
  - REM [Building JAVASCRIPT]
  - haxe tests.hxml -js bin/test.js
  - REM [Building PHP]
  - haxe tests.hxml -php bin/php
  - REM [Building PHP7]
  - haxe tests.hxml -D php7 -php bin/php7
  - REM [Building PYTHON]
  - haxe tests.hxml -python bin/test.py
  - REM [Building JAVA]
  - haxe tests.hxml -java bin/java
  - REM [Building C#]
  - haxe tests.hxml -cs bin/cs
  - REM [Building C++]
  - haxe tests.hxml -cpp bin/cpp

test_script:
  - REM [Running NEKO]
  - neko bin/test.n
  - REM [Running JAVASCRIPT]
  - node bin/test.js
  - REM [Running PHP]
  - php bin/php/index.php
  - REM [Running PHP7]
  - php bin/php7/index.php
  - REM [Running PYTHON]
  - python bin/test.py
  - REM [Running JAVA]
  - java -jar bin/java/TestAll.jar
  - REM [Running C#]
  - bin/cs/bin/TestAll.exe
  - REM [Running C++]
  - bin/cpp/TestAll.exe